name: Simple Build
on: pull_request

jobs:
  run-build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Run linters
        run: yarn lint

      - name: Run test
        run: yarn test

      - name: Run build
        run: yarn build